### ISSUE TITLE
Please make suggested search more on-topic

### ISSUE THREAD

**Issue by triska** [nikitavoloboev/learn-anything#941]
This is mostly a usability issue. For example, when I visit the [**prolog**](https://learn-anything.xyz/programming/programming_languages/prolog)&nbsp;node, the suggested search variously displays "Russian&nbsp;language", "javascript&nbsp;libraries" and "growth&nbsp;hacking".

In my opinion, it makes sense to show possible search topics on the entry page, but not so much when you are already visiting a specific&nbsp;node. Instead, I recommend to show either the actual node&nbsp;topic or its&nbsp;parent in the search&nbsp;box when you are already visiting a particular&nbsp;node.

Thank you!

**Comment by nikitavoloboev** [comment]
Hey @triska, thank you for writing the prolog book. I haven't had the chance to check it out yet but I will. :)

For the suggested searches, we decided to add them to promote new searches for new things you can learn. Since we have a very limited index (~ 500 searches), these suggestions are very helpful to users we think.

They are also greyed out to indicate that they are suggestions. There is no need to show the parent node in the search bar as one can already see it in the path below the search so as the node topic where the user currently is in.

**Comment by triska** [comment]
Regarding the book: You are welcome! I hope you find it useful, and thank you for the publicity.

I understand that promoting the index is useful, and it is good to show users what can be searched. However, as it currently is, at least I often wonder whether I have actually clicked on the correct&nbsp;page, because the suggestion is so prominently placed that it reads almost like a headline. Please consider making this more usable somehow, for example, by more prominently displaying the actual title of the&nbsp;node we are currently visiting. Thank&nbsp;you!

**Comment by nikitavoloboev** [comment]
That is actually a great point. We will try to show prominently where you actually are in the knowledge tree. (perhaps by bolding out the last node in the path)

**Comment by nikitavoloboev** [comment]
The text of current map is bolded now. :)
